linters:
  BangFormat:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true

  Indentation:
    character: space
    enabled: true
    exclude:
      - 'stylesheets/_css3.scss'

  MergeableSelector:
    enabled: true

  PropertySpelling:
    enabled: true

  SingleLinePerProperty:
    enabled: true

  TrailingSemicolon:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  # Disabled rules

  BorderZero:
    enabled: false
  ColorKeyword:
    enabled: false
  Comment:
    enabled: false
  Compass Linters:
    enabled: false
  DebugStatement:
    enabled: false
  DeclarationOrder:
    enabled: false
  ElsePlacement:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  HexLength:
    enabled: false
  HexNotation:
    enabled: false
  HexValidation:
    enabled: false
  IdWithExtraneousSelector:
    enabled: false
  ImportPath:
    enabled: false
  LeadingZero:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  Shorthand:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
  SpaceAfterPropertyName:
    enabled: false
  SpaceBeforeBrace:
    enabled: false
  SpaceBetweenParens:
    enabled: false
  StringQuotes:
    enabled: false
  TrailingZero:
    enabled: false
  UnnecessaryMantissa:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
  VendorPrefixes:
    enabled: false
  ZeroUnit:
    enabled: false
