name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source: explainer/index.html
            destination: explainer/index.html
          - source: guidelines/index.html
            destination: guidelines/index.html
          - source: requirements/index.html
            destination: requirements/index.html
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          GH_PAGES_BUILD_OVERRIDE: |
            lint: false
          BUILD_FAIL_ON: nothing
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
          GH_PAGES_BRANCH: gh-pages
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
